### ISSUE TITLE
Add Marathon backup/restore

### ISSUE THREAD

**Issue by lloesche** [dcos/dcos-cli#596] opened 2016-04-28 12:51 UTC
I'd like to be able to
`dcos marathon backup > backup.json`
`dcos marathon restore < backup.json`
Or in combination with what I propose in https://github.com/dcos/dcos-cli/issues/595 be able to
`dcos marathon backup --cluster=prod | dcos marathon restore --cluster=stage`

The backup procedure would have to clean up some of the information that the API returns like task information that needs to be discarded for example.

**Comment by jsancio** [comment] 2016-04-28 17:18
This is a feature for Marathon itself. We should allow Marathon to define how you backup and restore their state. cc @aquamatthias @air

**Comment by air** [comment] 2016-04-28 18:14
Tracking internally as https://mesosphere.atlassian.net/browse/MARATHON-976

**Comment by jsancio** [comment] 2016-06-29 22:37
This is a duplicate of #458. cc @aquamatthias

**Closed** 2016-06-29 22:37 UTC
